debug: false
price:
  enchantMultiplier:
    base: 2.0
    factor: 6.0
repairBlocks:
  singleRepair:
    block: 42
  completeRepair:
    block: 41
  cheapRepair:
    block: 57
    breakPercentage: 15
    costPercentage: 70
