price:
  perDamage: 0.5
  multiplicator:
    base: 2
    factor: 6
repairblocks:
  singleRepair:
    block: 42
  completeRepair:
    block: 41
  cheapRepair:
    block: 57
    breakPercentage: 15
    costPercentage: 70
