name: ItemRepair
version: "${project.version}"
main: de.codeinfection.quickwango.ItemRepair.ItemRepair
dev-url: http://dev.bukkit.org/server-mods/itemrepair
commands:
  itemrepair:
    usage: "/<command> <add|remove|reload>"
    description: "Command to manage Repair Blocks"
    aliases:
      - ir
depend:
  - Vault
website: "http://parallel-universe.de"
description: "Adds repair functionality to minecraft"
authors:
  - "Quick_Wango"
  - "VoLLi"
  - "Faithcaio"
