name: ItemRepair
version: "${project.version}"
main: de.codeinfection.VoLLi.ItemRepair.ItemRepair
commands:
  itemrepair:
    usage: "/<command> <add|remove>"
    description: "Command to manage Repair Blocks"
depend:
  - iConomy
softdepend: []
database: false
website: "http://parallel-universe.de"
description: ""
author: "VoLLi"
authors:
  - "Quick_Wango"
  - "VoLLi"
load: postworld
permissions:
  itemrepair.allblocks:
    description: "Allows the player to use all repair blocks"
    default: op
  itemrepair.commands.*:
    description: "Allows the player to use all commands"
    default: op
    children:
      itemrepair.commands.add: true
      itemrepair.commands.remove: true
  itemrepair.commands.add:
    description: "Allows the player to add repair blocks"
    default: op
  itemrepair.commands.remove:
    description: "Allows the player to remove repair blocks"
    default: op
