name: ItemRepair
version: "${project.version}"
main: de.codeinfection.VoLLi.ItemRepair.ItemRepair
dev-url: http://dev.bukkit.org/server-mods/ItemRepair
commands:
  itemrepair:
    usage: "/<command> <add|remove>"
    description: "Command to manage Repair Blocks"
depend:
  - Vault
website: "http://parallel-universe.de"
description: "Adds repair functionality to minecraft"
authors:
  - "Quick_Wango"
  - "VoLLi"
permissions:
  itemrepair.allblocks:
    description: "Allows the player to use all repair blocks"
    default: op
  itemrepair.commands.*:
    description: "Allows the player to use all commands"
    default: op
    children:
      itemrepair.commands.add: true
      itemrepair.commands.remove: true
  itemrepair.commands.add:
    description: "Allows the player to add repair blocks"
    default: op
  itemrepair.commands.remove:
    description: "Allows the player to remove repair blocks"
    default: op
